<table border="0" width="100%">
<?

$imieniny[1][1] = "Mieczys³awa i Mieszka";
$imieniny[1][2] = "Grzegorza i Izydora";
$imieniny[1][3] = "Genowefy i Danuty";
$imieniny[1][4] = "Anieli i El¿biety";
$imieniny[1][5] = "Hanny i Szymona";
$imieniny[1][6] = "Trzech Króli";
$imieniny[1][7] = "lucjana i Rajmunda";
$imieniny[1][8] = "Seweryna i M¶cis³awa";
$imieniny[1][9] = "Marceliny i Marcjanny";
$imieniny[1][10] = "Wilhelma i Danuty";
$imieniny[1][11] = "Honoraty i Matyldy";
$imieniny[1][12] = "Arkadiusza i Grety";
$imieniny[1][13] = "Bogumi³y i Weroniki";
$imieniny[1][14] = "Feliksa i Niny";
$imieniny[1][15] = "Paw³a i Arnolda";
$imieniny[1][16] = "Waldemara i Marcelego";
$imieniny[1][17] = "Antoniego i jana";
$imieniny[1][18] = "Piotra i Ma³gorzaty";
$imieniny[1][19] = "Henryka i Mariusza";
$imieniny[1][20] = "Fabina i Sebastiana";
$imieniny[1][21] = "Agnieszki i Jaros³awa";
$imieniny[1][22] = "Anastazego i Wincentego";
$imieniny[1][23] = "Ildefonsa i Rajmunda";
$imieniny[1][24] = "Felicji i Franciszka";
$imieniny[1][25] = "Paw³a i Mi³osza";
$imieniny[1][26] = "Tymoteusza i Pauliny";
$imieniny[1][27] = "Przybys³awa i Anieli";
$imieniny[1][28] = "Walerego i Radomira";
$imieniny[1][29] = "Zdzis³awa i Franciszka";
$imieniny[1][30] = "Macieja i Martyny";
$imieniny[1][31] = "Marceli i ludwika";
$imieniny[2][1] = "Brygidy i Ignacego";
$imieniny[2][2] = "Marii i Miros³awy";
$imieniny[2][3] = "B³a¿eja i Oskara";
$imieniny[2][4] = "Andrzeja i Weroniki";
$imieniny[2][5] = "Agaty i Adelajdy";
$imieniny[2][6] = "Doroty i Bogdana";
$imieniny[2][7] = "Ryszarda i Teodora";
$imieniny[2][8] = "Hieronima i Sebastiana";
$imieniny[2][9] = "Apolonii i Eryki";
$imieniny[2][10] = "Elwiry i Jacka";
$imieniny[2][11] = "Lucjana i Grzegorza";
$imieniny[2][12] = "Eulaii i Benedykta";
$imieniny[2][13] = "Grzegorza i Katarzyny";
$imieniny[2][14] = "Cyryla i Walentego";
$imieniny[2][15] = "Jowity i Faustyna";
$imieniny[2][16] = "Danuty Julianny";
$imieniny[2][17] = "Aleksego i £ukasza";
$imieniny[2][18] = "Konstancji i Zuzanny";
$imieniny[2][19] = "Arnolda i Konrada";
$imieniny[2][20] = "Leona i Ludomira";
$imieniny[2][21] = "Eleonory i Roberta";
$imieniny[2][22] = "Marty i Ma³gorzaty";
$imieniny[2][23] = "Romany i Damiana";
$imieniny[2][24] = "Macieja i Bogusza";
$imieniny[2][25] = "Wiktora i Cezarego";
$imieniny[2][26] = "Miros³awa i Bogumi³a";
$imieniny[2][27] = "Gabrieli i Anastazji";
$imieniny[2][28] = "Romana i Makarego";
$imieniny[2][29] = "Lecha i Lutos³awa";
$imieniny[3][1] = "Antoniny i Albina";
$imieniny[3][2] = "Heleny i Halszki";
$imieniny[3][3] = "Maryny i Kunegundy";
$imieniny[3][4] = "£ucji i Kazimierza";
$imieniny[3][5] = "Adriana i Teofila";
$imieniny[3][6] = "Agnieszki i Ró¿y";
$imieniny[3][7] = "Tomasza i Felicyty";
$imieniny[3][8] = "Beaty i Wincentego";
$imieniny[3][9] = "Katarzyny i Franciszki";
$imieniny[3][10] = "Cypriana i Marcela";
$imieniny[3][11] = "Ludos³awa i Benedykta";
$imieniny[3][12] = "Bernarda i Grzegorza";
$imieniny[3][13] = "Bo¿eny i Krystyny";
$imieniny[3][14] = "Leona i Matyldy";
$imieniny[3][15] = "Longina i Ludwiki";
$imieniny[3][16] = "Izabeli i Oktawii";
$imieniny[3][17] = "Patryka i Zbigniewa";
$imieniny[3][18] = "Cyryla i Edwarda";
$imieniny[3][19] = "Józefa i Bogdana";
$imieniny[3][20] = "Eufemii i Klaudii";
$imieniny[3][21] = "Lubomira i Benedykta";
$imieniny[3][22] = "Katarzyny i Bogus³awa";
$imieniny[3][23] = "Feliksa i Pelagii";
$imieniny[3][24] = "Gabriela i Marka";
$imieniny[3][25] = "Ireneusza i Marioli";
$imieniny[3][26] = "Emanuela i Teodora";
$imieniny[3][27] = "Ernesta i Lidii";
$imieniny[3][28] = "Anieli i Jana";
$imieniny[3][29] = "Amalii i Wiktoryna";
$imieniny[3][30] = "Anieli i Leonarda";
$imieniny[3][31] = "Dobromierza i Gwidona";
$imieniny[4][1] = "Gra¿yny i Ireny";
$imieniny[4][2] = "Franciszka i W³adys³awa";
$imieniny[4][3] = "Jakuba i Ryszarda";
$imieniny[4][4] = "Izydora i Wac³awa";
$imieniny[4][5] = "Ireny i Wincentego";
$imieniny[4][6] = "Celestyna i Izoldy";
$imieniny[4][7] = "Jana i Rufina";
$imieniny[4][8] = "Dionizego i Julii";
$imieniny[4][9] = "Marii i Dymitra";
$imieniny[4][10] = "Micha³a i Makarego";
$imieniny[4][11] = "Leona i Jaromira";
$imieniny[4][12] = "Juliusza i Zenona";
$imieniny[4][13] = "Przemys³awa i Marcina";
$imieniny[4][14] = "Justyna i Waleriana";
$imieniny[4][15] = "Anastazji i Wac³awy";
$imieniny[4][16] = "Ma³gorzaty i Szymona";
$imieniny[4][17] = "Roberta i Stefana";
$imieniny[4][18] = "Alicji i Bogus³awy";
$imieniny[4][19] = "Adolfa i Leona";
$imieniny[4][20] = "Agnieszki i Czes³awa";
$imieniny[4][21] = "Enzelma i Bartosza";
$imieniny[4][22] = "Leona i £ukasza";
$imieniny[4][23] = "Jerzego i Wojciecha";
$imieniny[4][24] = "Horacego i Fidelisa";
$imieniny[4][25] = "Marka i Jaros³awa";
$imieniny[4][26] = "Marzeny i Marii";
$imieniny[4][27] = "Felicji i Teofila";
$imieniny[4][28] = "Paw³a i Walerii";
$imieniny[4][29] = "Katarzyny i Rity";
$imieniny[4][30] = "Donata i Mariana";
$imieniny[5][1] = "Józefa i Jeremiasza";
$imieniny[5][2] = "Anastazego i Zygmunta";
$imieniny[5][3] = "Marii i Antoniny";
$imieniny[5][4] = "Moniki i Floriana";
$imieniny[5][5] = "Ireny i Waldemara";
$imieniny[5][6] = "Filipa i Judyty";
$imieniny[5][7] = "Ludmi³y i Benedykta";
$imieniny[5][8] = "Stanis³awa i Wiktora";
$imieniny[5][9] = "Grzegorza i Karoliny";
$imieniny[5][10] = "Antoniny i Izydora";
$imieniny[5][11] = "Miry i Igi";
$imieniny[5][12] = "Dominika i Pankracego";
$imieniny[5][13] = "Glorii i Serwacego";
$imieniny[5][14] = "Bonifacego i Macieja";
$imieniny[5][15] = "Izydora i Zofii";
$imieniny[5][16] = "Andrzeja i Szymona";
$imieniny[5][17] = "Weroniki i S³awomira";
$imieniny[5][18] = "Eryka i Feliksa";
$imieniny[5][19] = "Celestyna i Piotra";
$imieniny[5][20] = "Bernardyna i Aleksandra";
$imieniny[5][21] = "Wiktora i Tymoteusza";
$imieniny[5][22] = "Heleny i Wies³awy";
$imieniny[5][23] = "Iwony i Kryspina";
$imieniny[5][24] = "Joanny i Marii";
$imieniny[5][25] = "Grzegorza i Wiolety";
$imieniny[5][26] = "Filipa i Pauliny";
$imieniny[5][27] = "Juliana i Magdaleny";
$imieniny[5][28] = "Jaromira i Augustyna";
$imieniny[5][29] = "Urszuli i Bogus³awa";
$imieniny[5][30] = "Ferdynanda i Feliksa";
$imieniny[5][31] = "Anieli i Petroneli";
$imieniny[6][1] = "Konrada i Jakuba";
$imieniny[6][2] = "Piotra i Erazma";
$imieniny[6][3] = "Leszka i Karola";
$imieniny[6][4] = "Franciszka i Kwiryny";
$imieniny[6][5] = "Bonifacego i Walerii";
$imieniny[6][6] = "Klaudiusza i Norberta";
$imieniny[6][7] = "Roberta i Wies³awa";
$imieniny[6][8] = "Maksyma i Seweryna";
$imieniny[6][9] = "Felicjana i Pelagii";
$imieniny[6][10] = "Bogumi³a i Diany";
$imieniny[6][11] = "Barnaby i Radomi³a";
$imieniny[6][12] = "Janiny i Leona";
$imieniny[6][13] = "Antoniego i Lucjana";
$imieniny[6][14] = "Bazylego i Elizy";
$imieniny[6][15] = "Jolanty i Wita";
$imieniny[6][16] = "Aliny i Anety";
$imieniny[6][17] = "Adolfa i Laury";
$imieniny[6][18] = "Marka i El¿biety";
$imieniny[6][19] = "Gerwazego i Protazego";
$imieniny[6][20] = "Bogny i Florentyny";
$imieniny[6][21] = "Alicji i Alojzego";
$imieniny[6][22] = "Flawiusza i Tomasza";
$imieniny[6][23] = "Wandy i Zeonona";
$imieniny[6][24] = "Jana i Danuty";
$imieniny[6][25] = "Doroty i £ucji";
$imieniny[6][26] = "Jana i Paw³a";
$imieniny[6][27] = "W³adys³awa i Maryli";
$imieniny[6][28] = "Leona i Ireneusza";
$imieniny[6][29] = "Piotra i Paw³a";
$imieniny[6][30] = "Emilii i Lucyny";
$imieniny[7][1] = "Mariana i Haliny";
$imieniny[7][2] = "Jagody i Marii";
$imieniny[7][3] = "Anatola i Jacka";
$imieniny[7][4] = "El¿biety i Teodora";
$imieniny[7][5] = "Antoniego i Marii";
$imieniny[7][6] = "Dominiki i £ucji";
$imieniny[7][7] = "Cyryla i Metodego";
$imieniny[7][8] = "El¿biety i Eugeniusza";
$imieniny[7][9] = "Sylwii i Weroniki";
$imieniny[7][10] = "Almy i Witalisa";
$imieniny[7][11] = "Olgi i Kaliny";
$imieniny[7][12] = "Jana i Feliksa";
$imieniny[7][13] = "Ma³gorzaty i Ernesta";
$imieniny[7][14] = "Kamila i Izabeli";
$imieniny[7][15] = "Henryka i W³odzimierza";
$imieniny[7][16] = "Benity i Eustachego";
$imieniny[7][17] = "Anety i Bogdana";
$imieniny[7][18] = "Kamila i Szymona";
$imieniny[7][19] = "Marcina i Wincentego";
$imieniny[7][20] = "Czes³awa i Ma³gorzaty";
$imieniny[7][21] = "Daniela i Wiktora";
$imieniny[7][22] = "Marii i Magdaleny";
$imieniny[7][23] = "Brygidy i Bogny";
$imieniny[7][24] = "Krystyny i Olgi";
$imieniny[7][25] = "Krzysztofa i Jakuba";
$imieniny[7][26] = "Anny i Joachima";
$imieniny[7][27] = "Natalii i Julii";
$imieniny[7][28] = "Marceli i Ady";
$imieniny[7][29] = "Olafa i Konstantego";
$imieniny[7][30] = "Aldony i Donata";
$imieniny[7][31] = "Ignacego i Heleny";
$imieniny[8][1] = "Justyny i Jaros³awa";
$imieniny[8][2] = "Euzebiusza i Kariny";
$imieniny[8][3] = "Augusta i Lidii";
$imieniny[8][4] = "Dominika i Jana";
$imieniny[8][5] = "Emila i Marii";
$imieniny[8][6] = "Jakuba i S³awy";
$imieniny[8][7] = "Doroty i Kajetana";
$imieniny[8][8] = "Cypriana i Dominika";
$imieniny[8][9] = "Ireny i Romualda";
$imieniny[8][10] = "Borysa i Wawrzyñca";
$imieniny[8][11] = "Klary i Ligii";
$imieniny[8][12] = "Lecha i Innocentego";
$imieniny[8][13] = "Diany i Hipolita";
$imieniny[8][14] = "Maksymiliana i Alfreda";
$imieniny[8][15] = "Napoleona i Stelii";
$imieniny[8][16] = "Joachima i Rocha";
$imieniny[8][17] = "Jacka i Mirona";
$imieniny[8][18] = "Bronis³awa i Heleny";
$imieniny[8][19] = "Boles³awa i Jana";
$imieniny[8][20] = "Bernarda i Samuela";
$imieniny[8][21] = "Kazimiery i Joanny";
$imieniny[8][22] = "Cezarego i Marii";
$imieniny[8][23] = "Apolinarego i Filipa";
$imieniny[8][24] = "Bart³omieja i Jerzego";
$imieniny[8][25] = "Józefa i Patrycji";
$imieniny[8][26] = "Adrianny i Konstantego";
$imieniny[8][27] = "Cezarego i Teodora";
$imieniny[8][28] = "Augustyna i Patrycji";
$imieniny[8][29] = "Sabiny i Beaty";
$imieniny[8][30] = "Feliksa i Ró¿y";
$imieniny[8][31] = "Ramony i Rajmunda";
$imieniny[9][1] = "Bronis³awy i Idziego";
$imieniny[9][2] = "Juliana i Stefana";
$imieniny[9][3] = "Grzegorza i Izabeli";
$imieniny[9][4] = "Rozalii i Rocha";
$imieniny[9][5] = "Doroty i Wawrzyñca";
$imieniny[9][6] = "Beaty i Eugeniusza";
$imieniny[9][7] = "Melchiora i Reginy";
$imieniny[9][8] = "Marii i Serafina";
$imieniny[9][9] = "Piotra i ¦cibora";
$imieniny[9][10] = "Aldony i £ukasza";
$imieniny[9][11] = "Hiacynta i Prota";
$imieniny[9][12] = "Marii i Gwidona";
$imieniny[9][13] = "Jana i Eugenii";
$imieniny[9][14] = "Cypriana i Roksany";
$imieniny[9][15] = "Nikodema i Marii";
$imieniny[9][16] = "Edyty i Kornela";
$imieniny[9][17] = "Justyna i Roberta";
$imieniny[9][18] = "Ireny i Stanis³awa";
$imieniny[9][19] = "Konstancji i Teodora";
$imieniny[9][20] = "Filipiny i Eustachego";
$imieniny[9][21] = "Jonasza i Mateusza";
$imieniny[9][22] = "Joachima i Tomasza";
$imieniny[9][23] = "Bogus³awa i Tekli";
$imieniny[9][24] = "Gerarda i Teodora";
$imieniny[9][25] = "Aurelii i Kleofasa";
$imieniny[9][26] = "Damiana i Zbys³awa";
$imieniny[9][27] = "Mirabeli i Wincentego";
$imieniny[9][28] = "Marka i Wac³awa";
$imieniny[9][29] = "Micha³a i Rafa³a";
$imieniny[9][30] = "Hieronima i Honoriusza";
$imieniny[10][1] = "Danuty i Remigiusza";
$imieniny[10][2] = "Teofila i Dionizego";
$imieniny[10][3] = "Jana i Teresy";
$imieniny[10][4] = "Edwina i Franciszka";
$imieniny[10][5] = "Igora i Rajmunda";
$imieniny[10][6] = "Artura i Fryderyki";
$imieniny[10][7] = "Marii i Marka";
$imieniny[10][8] = "Pelagii i Walerii";
$imieniny[10][9] = "Dionizego i Wincentego";
$imieniny[10][10] = "Daniela i Przemys³awa";
$imieniny[10][11] = "Dobromiry i Emila";
$imieniny[10][12] = "Eustachego i Maksymiliana";
$imieniny[10][13] = "Edwarda i Gerarda";
$imieniny[10][14] = "Bernarda i Liwii";
$imieniny[10][15] = "Jadwigi i Teresy";
$imieniny[10][16] = "Ambro¿ego i Marty";
$imieniny[10][17] = "Wiktora i Lucyny";
$imieniny[10][18] = "Juliana i £ukasza";
$imieniny[10][19] = "Paw³a i Ziemowita";
$imieniny[10][20] = "Jana i Kleopatry";
$imieniny[10][21] = "Jakuba i Urszuli";
$imieniny[10][22] = "Filipa i Halki";
$imieniny[10][23] = "Marleny i Seweryna";
$imieniny[10][24] = "Antoniego i Marcina";
$imieniny[10][25] = "Bonifacego i Darii";
$imieniny[10][26] = "Ewarysta i Damiana";
$imieniny[10][27] = "Sabiny i Wincentego";
$imieniny[10][28] = "Tadeusza i Szymona";
$imieniny[10][29] = "Felicjana i Wiolety";
$imieniny[10][30] = "Edmunda i Przemys³awa";
$imieniny[10][31] = "£ukasza i Saturnina";
$imieniny[11][1] = "Wszystkich ¦wiêtych";
$imieniny[11][2] = "Tobiasza i Bohdany";
$imieniny[11][3] = "Marcina i Huberta";
$imieniny[11][4] = "Karola i Olgierda";
$imieniny[11][5] = "El¿biety i S³awomira";
$imieniny[11][6] = "Ziemowita i Jacka";
$imieniny[11][7] = "Antoniego i Ernesta";
$imieniny[11][8] = "Klaudii i Seweryna";
$imieniny[11][9] = "Anatola i Genowefy";
$imieniny[11][10] = "Leona i Ludomira";
$imieniny[11][11] = "Marcina i Bart³omieja";
$imieniny[11][12] = "Renaty i Mateusza";
$imieniny[11][13] = "Stanis³awa i Benedykta";
$imieniny[11][14] = "Wawrzyñca i Agaty";
$imieniny[11][15] = "Alberta i Leopolda";
$imieniny[11][16] = "Marii i Ma³gorzaty";
$imieniny[11][17] = "El¿biety i Grzegorza";
$imieniny[11][18] = "Karoliny i Romana";
$imieniny[11][19] = "Salomei i Seweryna";
$imieniny[11][20] = "Anatola i Rafa³a";
$imieniny[11][21] = "Juliusza i Konrada";
$imieniny[11][22] = "Stefana i Marka";
$imieniny[11][23] = "Adeli i Klemensa";
$imieniny[11][24] = "Emmy i Flory";
$imieniny[11][25] = "Erazma i Katarzyny";
$imieniny[11][26] = "Konrada i Leonarda";
$imieniny[11][27] = "Maksyma i Waleriana";
$imieniny[11][28] = "Zdzis³awa i Natalii";
$imieniny[11][29] = "B³a¿eja i Fryderyka";
$imieniny[11][30] = "Andrzeja i Konstantego";
$imieniny[12][1] = "Eligiusza i Natalii";
$imieniny[12][2] = "Balbiny i Pauliny";
$imieniny[12][3] = "Franciszka i Ksawerego";
$imieniny[12][4] = "Hieronima i Barbary";
$imieniny[12][5] = "Edyty i Kryspina";
$imieniny[12][6] = "Jaremy i Miko³aja";
$imieniny[12][7] = "Marcina i Teodora";
$imieniny[12][8] = "Marii i Makarego";
$imieniny[12][9] = "Leokadii i Wies³awa";
$imieniny[12][10] = "Daniela i Julii";
$imieniny[12][11] = "Damazego i Waldemara";
$imieniny[12][12] = "Joanny i Dagmary";
$imieniny[12][13] = "£ucji i Otylii";
$imieniny[12][14] = "Izydora i Jana";
$imieniny[12][15] = "Niny i Waleriana";
$imieniny[12][16] = "Alicji i Zdzis³awy";
$imieniny[12][17] = "Olimpii i £azarza";
$imieniny[12][18] = "Bogus³awa i Laurencji";
$imieniny[12][19] = "Dariusza i Gabrieli";
$imieniny[12][20] = "Juliusza i Dominika";
$imieniny[12][21] = "Piotra i Tomasza";
$imieniny[12][22] = "Honoraty i Zenona";
$imieniny[12][23] = "Jana i Wiktorii";
$imieniny[12][24] = "Ewy i Adama";
$imieniny[12][25] = "Anastazji i Eugenii";
$imieniny[12][26] = "Dionizego i Szczepana";
$imieniny[12][27] = "Jana i Maksyma";
$imieniny[12][28] = "Cezarego i Teofili";
$imieniny[12][29] = "Tomasza i Dominika";
$imieniny[12][30] = "Irmy i Eugeniusza";
$imieniny[12][31] = "Sylwestra i Melanii";

	$dz_tyg=array("Sun"=>"Niedziela","Mon"=>"Poniedzia³ek","Tue"=>"Wtorek","Wed"=>"¦roda","Thu"=>"Czwartek","Fri"=>"Pi±tek","Sat"=> "Sobota");
		if ($dz=gmDate("D"))
			{
			$dz_tyg="$dz_tyg[$dz]";
			}

	$dzien=date("d");

	$miesiac=array(1=>"Stycznia","Lutego","Marca","Kwietnia","Maja","Czerwca","Lipca","Sierpnia","Wrze¶nia","Pa¼dziernika","Listopada","Grudnia");
		if ($m=gmDate("n"))
			{
			$miesiac="$miesiac[$m]";
			}

	$rok=gmDate("Y");


if($dz_tyg == "sobota")
{
$dzien = '<font color="green" size="7">'. $dzien .'</font>';
}
elseif($dz_tyg == "niedziela")
{
$dzien = '<font color="red" size="7">'. $dzien .'</font>';
}
else
{
$dzien = '<font size="7">'. $dzien .'</font>';
}

$i_m = date("n");
$i_d = date("j");

echo '
 <tr>
  <td align="center">'. $dz_tyg .'</td>
 </tr>
 <tr>
  <td align="center"><b>'. $dzien .'</b></td>
 </tr>
 <tr>
  <td align="center">'. $miesiac .' '. $rok .'</td>
 </tr>
 <tr>
  <td align="center">&nbsp;</td>
 </tr>
 <tr>
  <td align="center">Imieniny:</td>
 </tr>
 <tr>
  <td align="center"><b>'. $imieniny[$i_m][$i_d].'</b></td>
 </tr>';
?>
</table>
